### PR TITLE
Add PVC Count Quota Controls to Registry

### LINKED ISSUE #341: Implement API Changes for PVC Count

### LINKED ISSUE #342: Implement PVC Count Display for Registry Frontend

### LINKED ISSUE #343: Implement DB Changes for PVC Count Quota Control

### PR DESCRIPTION
**Pull request by yhfreeman**
- Fronted Updated to show PVC Count per Quota Size
Fixes #342 
- API Updated to Pull the PVC Count from the DB and Pass it through NATS
Fixes #341 
- DB Updated with PVC Count field
Fixes #343

### CODE REVIEW

**Comment by yhfreeman** [comment]
Might need adjustment @ pvcCount in JSON msg to bot, pls see https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/13#issuecomment-849992365

**Comment by yhfreeman** [comment]
The migration version on file name `db/sql/V2.3__add_pvc_count_ref_quota_alter.sql` is based on the assumption that [V2.2__dashboard_approval_auto_merge.sql](https://github.com/bcgov/platform-services-registry/blob/96148507f4bd8e0a31bb43a767a867224bca71d1/db/sql/V2.2__dashboard_approval_auto_merge.sql) gets in first.

**Comment by yhfreeman** [comment]
@sbathgate FYI^^^

**Review by sbathgate — COMMENTED** [review]
Holding merge until Dashboard approvals PR is merged to avoid flyway migration conflict.

**Review by sbathgate — APPROVED** [review]
With changes included in PR #428 this will be good to merge, upon approval of #428.

**Pull request merged**
